version: 2.1

parameters:
  site_title:
    type: string
    default: 'Pseudoviz'
  site_description:
    type: string
    default: 'All about dataviz'
  site_data:
    type: string
    default: 'https://s3.amazonaws.com/uploads.dskt.ch/datasketch/pseudoviz/pseudoviz-es.json'

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.0.0
  aws-s3: circleci/aws-s3@4.0.0

jobs:
  build:
    executor:
      name: node/default
      tag: '18.17'
    environment:
      SITE_TITLE: << pipeline.parameters.site_title >>
      SITE_DESCRIPTION: << pipeline.parameters.site_description >>
      SITE_DATA: << pipeline.parameters.site_data >>
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: mkdir ~/out
      - persist_to_workspace:
          root: ~/out
          paths:
            - ./dist
      - run: ls -la ~
  deploy:
    executor: aws-s3/default
    steps:
      - run: pwd
      - attach_workspace:
          at: ~/build
      - aws-cli/setup
      - aws-s3/sync:
          from: './dist/'
          to: 's3://sites.dskt.ch/datasketch/pseudoviz'

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
