version: 2.1

parameters:
  title:
    type: string
    default: ''
  description:
    type: string
    default: ''
  org:
    type: string
    default: ''
  db:
    type: string
    default: ''
  table:
    type: string
    default: ''
  cardTitle:
    type: string
    default: ''
  cardDescription:
    type: string
    default: ''
  cardImage:
    type: string
    default: ''
  cardSlug:
    type: string
    default: ''
  run_workflow:
    type: boolean
    default: false

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: '18.17'
    environment:
      SITE_TITLE: << pipeline.parameters.title >>
      SITE_DESCRIPTION: << pipeline.parameters.description >>
      SITE_DATA: https://s3.amazonaws.com/uploads.dskt.ch/<< pipeline.parameters.org >>/<< pipeline.parameters.db >>/<< pipeline.parameters.table >>.json
      CARD_TITLE: <<pipeline.parameters.cardTitle>>
      CARD_DESCRIPTION: <<pipeline.parameters.cardDescription>>
      CARD_IMAGE: <<pipeline.parameters.cardImage>>
      CARD_SLUG: <<pipeline.parameters.cardSlug>>
    steps:
      - checkout
      - run: echo $SITE_DATA
      - node/install-packages
      - run: npm run build -- --site https://sites.dskt.ch --base /<< pipeline.parameters.org >>/<< pipeline.parameters.db >>
      - persist_to_workspace:
          root: ~/
          paths:
            - project/dist
  deploy:
    executor:
      name: node/default
      tag: '18.17'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "eb:7d:2a:71:c2:6f:0c:87:4c:c8:32:8a:c1:2b:bc:55"
      - attach_workspace:
          at: ~/
      - run:
          name: Add github.com to known hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Update repo
          command: |
            git clone git@github.com:datasketch/users-generated-sites.git --depth 1
            cd users-generated-sites
            git config user.email "gh-machine@datasketch.co"
            git config user.name "machine-user"
            mkdir -p src/<< pipeline.parameters.org >>/<< pipeline.parameters.db >>
            cp -r ../dist/* ./src/<< pipeline.parameters.org >>/<< pipeline.parameters.db >>
            git add .
            git commit -m "Update builds" --allow-empty
            git push origin main

workflows:
  build_and_deploy:
    when: << pipeline.parameters.run_workflow >>
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
