version: 2.1

parameters:
  site_title:
    type: string
    default: 'Pseudoviz'
  site_description:
    type: string
    default: 'All about dataviz'
  org:
    type: string
    default: 'datasketch'
  db:
    type: string
    default: 'pseudoviz'
  table:
    type: string
    default: 'pseudoviz-en'
  run_workflow:
    type: boolean
    default: false

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.0.0
  aws-s3: circleci/aws-s3@4.0.0

jobs:
  build:
    executor:
      name: node/default
      tag: '18.17'
    environment:
      SITE_TITLE: << pipeline.parameters.site_title >>
      SITE_DESCRIPTION: << pipeline.parameters.site_description >>
      SITE_DATA: https://s3.amazonaws.com/uploads.dskt.ch/<< pipeline.parameters.org >>/<< pipeline.parameters.db >>/<< pipeline.parameters.table >>.json
    steps:
      - checkout
      - run: echo $SITE_DATA
      - node/install-packages
      - run: npm run build -- --site https://sites.dskt.ch --base /<< pipeline.parameters.org >>/<< pipeline.parameters.db >>
      - persist_to_workspace:
          root: ~/
          paths:
            - project/dist
  deploy:
    executor: aws-s3/default
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - aws-s3/sync:
          from: './dist/'
          to: 's3://sites.dskt.ch/<< pipeline.parameters.org >>/<< pipeline.parameters.db >>'

workflows:
  build_and_deploy:
    when: << pipeline.parameters.run_workflow >>
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
